# Generated by Django 2.2 on 2022-01-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=40)),
                ('perishable', models.BooleanField()),
                ('weight', models.FloatField()),
                ('hunger', models.IntegerField()),
                ('thirst', models.IntegerField()),
                ('boredom', models.IntegerField()),
                ('unhappiness', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
