# Generated by Django 2.2 on 2022-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('isEditor', models.BooleanField()),
                ('password', models.CharField(max_length=40)),
                ('confirmPassword', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='users',
            field=models.ManyToManyField(related_name='foods', to='pzdata.User'),
        ),
    ]
