# Generated by Django 2.2 on 2022-01-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzdata', '0002_auto_20220121_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='users',
        ),
        migrations.AddField(
            model_name='food',
            name='favoriters',
            field=models.ManyToManyField(related_name='favorites', to='pzdata.User'),
        ),
    ]
