# Generated by Django 2.2 on 2022-01-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzdata', '0003_auto_20220123_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='favoriters',
            field=models.ManyToManyField(related_name='favorite_foods', to='pzdata.User'),
        ),
    ]
